name: Build Jazle DS

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - uses: actions/setup-python@v3
        with:
          python-version: '2.x'
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Generate WordleDS mod files for Jazle
        run: |
          deno run --allow-write --allow-read --allow-net jazle/process_safe.ts
      - name: Move Everything for packaging
        run: |
          cd jazle
          mkdir -p mod/jazle
          mv mod.json mod/jazle/
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: "jazle/mod"
          name: Mod ZIP
